<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PenerimaBantuanSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'nik'             => '7317011001750001',
                'nama_lengkap'    => 'Baharuddin Sangaji',
                'tempat_lahir'    => 'Lamasi',
                'tanggal_lahir'   => '1975-01-10',
                'jenis_kelamin'   => 'L',
                'alamat'          => 'Jl. Poros Lamasi No. 12',
                'rt'              => '001',
                'rw'              => '002',
                'kelurahan'       => 'Lamasi',
                'kecamatan'       => 'Lamasi',
                'kabupaten'       => 'Luwu',
                'no_hp'           => '081234567801',
                'foto_ktp'        => null,
                'kategori_miskin' => 'Sangat Miskin',
                'status_aktif'    => 'Aktif',
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nik'             => '7317015502800002',
                'nama_lengkap'    => 'Siti Rahmawati',
                'tempat_lahir'    => 'Palopo',
                'tanggal_lahir'   => '1980-02-15',
                'jenis_kelamin'   => 'P',
                'alamat'          => 'Dusun Lamasi Pantai',
                'rt'              => '002',
                'rw'              => '001',
                'kelurahan'       => 'Lamasi',
                'kecamatan'       => 'Lamasi',
                'kabupaten'       => 'Luwu',
                'no_hp'           => '081234567802',
                'foto_ktp'        => null,
                'kategori_miskin' => 'Miskin',
                'status_aktif'    => 'Aktif',
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nik'             => '7317011506600003',
                'nama_lengkap'    => 'Marthen Sulle',
                'tempat_lahir'    => 'Toraja',
                'tanggal_lahir'   => '1960-06-15',
                'jenis_kelamin'   => 'L',
                'alamat'          => 'Jl. Pahlawan No. 4',
                'rt'              => '001',
                'rw'              => '003',
                'kelurahan'       => 'Lamasi',
                'kecamatan'       => 'Lamasi',
                'kabupaten'       => 'Luwu',
                'no_hp'           => '081234567803',
                'foto_ktp'        => null,
                'kategori_miskin' => 'Sangat Miskin',
                'status_aktif'    => 'Aktif',
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nik'             => '7317016208880004',
                'nama_lengkap'    => 'Nurjannah',
                'tempat_lahir'    => 'Lamasi',
                'tanggal_lahir'   => '1988-08-22',
                'jenis_kelamin'   => 'P',
                'alamat'          => 'Jl. Perintis Kemerdekaan No. 45',
                'rt'              => '003',
                'rw'              => '002',
                'kelurahan'       => 'Lamasi',
                'kecamatan'       => 'Lamasi',
                'kabupaten'       => 'Luwu',
                'no_hp'           => '081234567804',
                'foto_ktp'        => null,
                'kategori_miskin' => 'Miskin',
                'status_aktif'    => 'Aktif',
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nik'             => '7317012211920005',
                'nama_lengkap'    => 'Yohanes Rante',
                'tempat_lahir'    => 'Lamasi',
                'tanggal_lahir'   => '1992-11-22',
                'jenis_kelamin'   => 'L',
                'alamat'          => 'Kompleks Pasar Lama',
                'rt'              => '002',
                'rw'              => '002',
                'kelurahan'       => 'Lamasi',
                'kecamatan'       => 'Lamasi',
                'kabupaten'       => 'Luwu',
                'no_hp'           => '081234567805',
                'foto_ktp'        => null,
                'kategori_miskin' => 'Rentan Miskin',
                'status_aktif'    => 'Aktif',
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nik'             => '7317010403700006',
                'nama_lengkap'    => 'Kaharuddin',
                'tempat_lahir'    => 'Belopa',
                'tanggal_lahir'   => '1970-03-04',
                'jenis_kelamin'   => 'L',
                'alamat'          => 'Jl. Trans Sulawesi RT 03',
                'rt'              => '003',
                'rw'              => '001',
                'kelurahan'       => 'Lamasi',
                'kecamatan'       => 'Lamasi',
                'kabupaten'       => 'Luwu',
                'no_hp'           => '081234567806',
                'foto_ktp'        => null,
                'kategori_miskin' => 'Miskin',
                'status_aktif'    => 'Aktif',
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nik'             => '7317014912650007',
                'nama_lengkap'    => 'Maria Somba',
                'tempat_lahir'    => 'Toraja',
                'tanggal_lahir'   => '1965-12-09',
                'jenis_kelamin'   => 'P',
                'alamat'          => 'Jl. Gereja Tua No. 8',
                'rt'              => '001',
                'rw'              => '001',
                'kelurahan'       => 'Lamasi',
                'kecamatan'       => 'Lamasi',
                'kabupaten'       => 'Luwu',
                'no_hp'           => '081234567807',
                'foto_ktp'        => null,
                'kategori_miskin' => 'Sangat Miskin',
                'status_aktif'    => 'Aktif',
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nik'             => '7317011804850008',
                'nama_lengkap'    => 'Agus Salim',
                'tempat_lahir'    => 'Lamasi',
                'tanggal_lahir'   => '1985-04-18',
                'jenis_kelamin'   => 'L',
                'alamat'          => 'Jl. Mesjid Raya',
                'rt'              => '002',
                'rw'              => '003',
                'kelurahan'       => 'Lamasi',
                'kecamatan'       => 'Lamasi',
                'kabupaten'       => 'Luwu',
                'no_hp'           => '081234567808',
                'foto_ktp'        => null,
                'kategori_miskin' => 'Rentan Miskin',
                'status_aktif'    => 'Aktif',
                'created_at'      => date('Y-m-d H:i:s'),
                'updated_at'      => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('penerima_bantuan')->insertBatch($data);

        // Seed initial Pengajuan
        $pengajuanData = [
            [
                'penerima_id'        => 1,
                'jenis_bantuan_id'   => 1, // PKH
                'tanggal_pengajuan'  => date('Y-m-01', strtotime('-2 months')),
                'status'             => 'Disetujui',
                'keterangan'         => 'Pengajuan bantuan sosial PKH Tahap 1',
                'catatan_verifikasi' => 'Memenuhi kriteria keluarga prasejahtera dengan tanggungan sekolah',
                'diajukan_oleh'      => 2, // petugas
                'diverifikasi_oleh'  => 3, // lurah
                'created_at'         => date('Y-m-d H:i:s', strtotime('-2 months')),
                'updated_at'         => date('Y-m-d H:i:s', strtotime('-2 months')),
            ],
            [
                'penerima_id'        => 2,
                'jenis_bantuan_id'   => 2, // BLT
                'tanggal_pengajuan'  => date('Y-m-05', strtotime('-1 months')),
                'status'             => 'Disetujui',
                'keterangan'         => 'Pengajuan BLT Dana Desa',
                'catatan_verifikasi' => 'Data terverifikasi layak menerima bantuan',
                'diajukan_oleh'      => 2,
                'diverifikasi_oleh'  => 3,
                'created_at'         => date('Y-m-d H:i:s', strtotime('-1 months')),
                'updated_at'         => date('Y-m-d H:i:s', strtotime('-1 months')),
            ],
            [
                'penerima_id'        => 3,
                'jenis_bantuan_id'   => 4, // Bantuan Lansia
                'tanggal_pengajuan'  => date('Y-m-10', strtotime('-1 months')),
                'status'             => 'Disetujui',
                'keterangan'         => 'Bantuan sosial kategori lansia terlantar',
                'catatan_verifikasi' => 'Hasil survei lapangan memenuhi syarat',
                'diajukan_oleh'      => 2,
                'diverifikasi_oleh'  => 3,
                'created_at'         => date('Y-m-d H:i:s', strtotime('-1 months')),
                'updated_at'         => date('Y-m-d H:i:s', strtotime('-1 months')),
            ],
            [
                'penerima_id'        => 4,
                'jenis_bantuan_id'   => 3, // BPNT
                'tanggal_pengajuan'  => date('Y-m-15'),
                'status'             => 'Menunggu',
                'keterangan'         => 'Pengajuan bantuan BPNT Sembako',
                'catatan_verifikasi' => null,
                'diajukan_oleh'      => 2,
                'diverifikasi_oleh'  => null,
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'penerima_id'        => 5,
                'jenis_bantuan_id'   => 2, // BLT
                'tanggal_pengajuan'  => date('Y-m-18'),
                'status'             => 'Menunggu',
                'keterangan'         => 'Pengajuan BLT Dana Desa',
                'catatan_verifikasi' => null,
                'diajukan_oleh'      => 2,
                'diverifikasi_oleh'  => null,
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
            [
                'penerima_id'        => 8,
                'jenis_bantuan_id'   => 5, // Beras CPP
                'tanggal_pengajuan'  => date('Y-m-20'),
                'status'             => 'Ditolak',
                'keterangan'         => 'Pengajuan bantuan beras CPP',
                'catatan_verifikasi' => 'Sudah menerima bantuan dari program daerah lain',
                'diajukan_oleh'      => 2,
                'diverifikasi_oleh'  => 3,
                'created_at'         => date('Y-m-d H:i:s'),
                'updated_at'         => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('pengajuan_bantuan')->insertBatch($pengajuanData);

        // Seed initial Penyaluran
        $penyaluranData = [
            [
                'pengajuan_id'        => 1,
                'tanggal_penyaluran'  => date('Y-m-15', strtotime('-2 months')),
                'jumlah_bantuan'      => 750000.00,
                'satuan'              => 'Rupiah',
                'metode_penyaluran'   => 'Transfer',
                'bukti_penyaluran'    => null,
                'keterangan'          => 'Penyaluran via Bank Himbara PKH',
                'status_penyaluran'   => 'Tersalurkan',
                'disalurkan_oleh'     => 2,
                'created_at'          => date('Y-m-d H:i:s', strtotime('-2 months')),
                'updated_at'          => date('Y-m-d H:i:s', strtotime('-2 months')),
            ],
            [
                'pengajuan_id'        => 2,
                'tanggal_penyaluran'  => date('Y-m-20', strtotime('-1 months')),
                'jumlah_bantuan'      => 300000.00,
                'satuan'              => 'Rupiah',
                'metode_penyaluran'   => 'Tunai',
                'bukti_penyaluran'    => null,
                'keterangan'          => 'Penyaluran tunai di Kantor Kelurahan Lamasi',
                'status_penyaluran'   => 'Tersalurkan',
                'disalurkan_oleh'     => 2,
                'created_at'          => date('Y-m-d H:i:s', strtotime('-1 months')),
                'updated_at'          => date('Y-m-d H:i:s', strtotime('-1 months')),
            ],
            [
                'pengajuan_id'        => 3,
                'tanggal_penyaluran'  => date('Y-m-22', strtotime('-1 months')),
                'jumlah_bantuan'      => 600000.00,
                'satuan'              => 'Rupiah',
                'metode_penyaluran'   => 'Tunai',
                'bukti_penyaluran'    => null,
                'keterangan'          => 'Penyaluran langsung ke rumah lansia di Lamasi',
                'status_penyaluran'   => 'Tersalurkan',
                'disalurkan_oleh'     => 2,
                'created_at'          => date('Y-m-d H:i:s', strtotime('-1 months')),
                'updated_at'          => date('Y-m-d H:i:s', strtotime('-1 months')),
            ],
        ];

        $this->db->table('penyaluran_bantuan')->insertBatch($penyaluranData);
    }
}
